# Generated by Django 3.2 on 2023-03-20 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='un_of_me',
        ),
        migrations.AddField(
            model_name='favorites',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='main.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_sub', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='sub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.related.ForeignKey, related_name='sub', to='users.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IngredientsToRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('un_of_me', models.CharField(max_length=30)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_recipe', to='main.ingredients')),
            ],
            options={
                'ordering': ['ingredient'],
            },
        ),
    ]
