# Generated by Django 3.2 on 2023-04-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230410_0826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientstorecipe',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
