# Generated by Django 3.2 on 2023-03-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230320_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientstorecipe',
            name='un_of_me',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='un_of_me',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
