# Generated by Django 3.2 on 2023-03-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230320_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientstorecipe',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ing_amount', to='main.recipe'),
            preserve_default=False,
        ),
    ]
