# Generated by Django 3.2 on 2023-03-22 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20230321_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ingredientstorecipe',
            options={},
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='un_of_me',
        ),
        migrations.RemoveField(
            model_name='ingredientstorecipe',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredientstorecipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientstorecipe',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
