# Generated by Django 3.2 on 2023-03-25 13:28

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_subscriptions_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('author', 'sub'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, sub=django.db.models.expressions.F('author')), name='check_sub'),
        ),
    ]
