# Generated by Django 3.2 on 2023-03-25 13:29

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230325_1328'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='check_sub',
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, sub=django.db.models.expressions.F('author')), name='its_not_allowed_to_follow_on_yourself'),
        ),
    ]
