# Generated by Django 3.2 on 2023-03-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230325_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['-id']},
        ),
    ]
