# Generated by Django 3.2 on 2023-03-29 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20230328_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobuylist',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='main.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tobuylist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientstorecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='main.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='tobuylist',
            unique_together={('user', 'recipe')},
        ),
    ]
