# Generated by Django 3.2 on 2023-03-29 19:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20230329_1943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToBuyList',
            new_name='Basket',
        ),
    ]
