# Generated by Django 3.2 on 2023-03-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_tobuylist_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['-id']},
        ),
    ]
