version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - pgdata:/var/lib/postgres/data/
    env_file:
      - ../backend/foodgram_back/.env
  webapp:
    depends_on:
      - db
    build:
      context: ../backend/foodgram_back/
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - ../backend/foodgram_back/.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
      - webapp
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    depends_on:
      - webapp
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      # - static_value:/data/www/static/
      # - media_value:/data/www/media/

volumes:
  static_value:
  media_value:
  pgdata: