version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - pgdata:/var/lib/postgres/data/
    env_file:
      - ../backend/foodgram_back/.env
  webapp:
    depends_on:
      - db
    build:
      context: ../backend/foodgram_back/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
      - 3000:3000
    env_file:
      - ../backend/foodgram_back/.env
    volumes:
      - media_value:/app/media/
      - static_value:/app/static/
  frontend:
    image: grindelwaldoff/foodgram_front:latest
    depends_on:
      - webapp
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    depends_on:
      - webapp
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  static_value:
  media_value:
  pgdata: