# Generated by Django 3.2 on 2023-06-27 12:06

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите значение', max_length=150, unique=True, verbose_name='Название:')),
                ('measurement_unit', models.CharField(help_text='Укажите единицу измерения ингредиента (г, кг, мл, л и тд)', max_length=50, verbose_name='Ед. измерения:')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IngredientsToRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Введите кол-во игредиента (гр, л, мл и тд.)', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Кол-во:')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите значение', max_length=150, validators=[django.core.validators.RegexValidator(message='Название рецепта должно содержать только буквы и цифры', regex='^[a-zA-Z0-9]*$')], verbose_name='Название:')),
                ('img', models.ImageField(help_text='Загрузите изображение', upload_to='recipes/', verbose_name='Изображении рецепта:')),
                ('description', models.CharField(help_text='Укажите основные этапы готовки', max_length=5000, verbose_name='Описание:')),
                ('time_to_cook', models.PositiveSmallIntegerField(help_text='Введите значение', validators=[django.core.validators.MinValueValidator(3)], verbose_name='Время приготовления:')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите значение', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Название тэга должно содержать только буквы и цифры', regex='^[a-zA-Z0-9]*$')], verbose_name='Название:')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', help_text='Выберите понравившийся из палитры', image_field=None, max_length=18, samples=None, verbose_name='Цвет тэга:')),
                ('slug', models.SlugField(help_text='Рекомендуется вводить название переведенное на английский*', max_length=150, unique=True, verbose_name='Название в ссылки на тэг:')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
