# Generated by Django 3.2 on 2023-06-23 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Введите значение', max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_username', message=('Название рецепта должно содержать только буквы и цифры',), regex='^[a-zA-Z0-9]*$')], verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(help_text='Введите значение', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message=('Название тэга должно содержать только буквы и цифры',), regex='^[a-zA-Z0-9]*$')], verbose_name='Название:'),
        ),
    ]
