# Generated by Django 3.2 on 2023-06-27 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230627_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Введите значение', max_length=150, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только буквы и цифры', regex='^[а-яА-Яa-zA-Z0-9]+$')], verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(help_text='Введите значение', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только буквы и цифры', regex='^[а-яА-Яa-zA-Z0-9]+$')], verbose_name='Название:'),
        ),
    ]
