# Generated by Django 3.2 on 2023-04-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reworkeduser',
            options={'ordering': ['-id']},
        ),
    ]
