# Generated by Django 3.2 on 2023-06-23 19:30

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reworkeduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_username', message=('Имя пользователя должно содержать только буквы и цифры',), regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='reworkeduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_username', message=('Фамилия пользователя должна содержать только буквы и цифры',), regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='reworkeduser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.RegexValidator(code='invalid_username', message=('Никнейм пользователя должен содержать только буквы и цифры',), regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
