# Generated by Django 3.2 on 2023-06-27 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230627_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reworkeduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только буквы', regex='^[а-яА-Яa-zA-Z]+$ ')]),
        ),
        migrations.AlterField(
            model_name='reworkeduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только буквы', regex='^[а-яА-Яa-zA-Z]+$ ')]),
        ),
    ]
