name: Foodgram-workflow

on: [push]

jobs:
  pep8_and_pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r backend/foodgram_back/requirements.txt
      # - name: Pytest
      #   run: |
      #     pytest
      - name: Pep8 check
        run: |
          python -m flake8
          cd backend/foodgram_back
          python manage.py test
  push_to_Docker:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    needs: pep8_and_pytest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: grindelwaldoff/foodgram_actions
  deploy:
    runs-on: ubuntu-latest
    name: deploy on Yandex Cloud
    needs: push_to_Docker
    steps:
      - name: executing remote ssh commands for deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull grindelwaldoff/foodgram_actions
            sudo docker stop $(sudo docker container stop ps -qa)
            sudo docker run --rm -d -p 8000:8000 grindelwaldoff/infra_ations
  telegram:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "${{ github.workflow }} запущенный ${{ github.actor }} в репозитории ${{ github.repository }} успешно выполнен! \n
            Комментарий: ${{ github.event.commits[0].message }} \n
            https://github.com/${{ github.repository }}/commit/${{github.sha}}"