name: Foodgram-workflow

on: [push]

jobs:
  pep8_and_pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r backend/foodgram_back/requirements.txt
      # - name: Pytest
      #   run: |
      #     pytest
      - name: Pep8 check
        run: |
          python -m flake8
          cd backend/foodgram_back
          python manage.py test
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRMA_TOKEN }}
          message: "${{ github.workflow }} запущенный ${{ github.actor }} в репозитории ${{ github.repository }} успешно выполнен! \n
            Комментарий: ${{ github.event.commits[0].message }} \n
            https://github.com/${{ github.repository }}/commit/${{github.sha}}"